#
# Configuration du site
# à recopier dans /content/site/config.yaml
#

# TITRE
params:
  title: "TITRE DU SITE"
  subtitle: "Sous-titre du site"
  # l'image arrondie
  avatar: "/img/hugo.png"
  # l'icône dans l'onglet du navigateur
  favicon: "/img/hugoSM.png"
  # l'image d'arrière plan
  backgroundImage: "/img/hugo-background.jpg"

# Les menus que l'on peut ajouter
menu:
  links: # menu qui va apparaître en bas de la carte du sommaire
  - name: "Documentation Beedream"
    url: "https://beedream.billerot.eu"
    weight: 10 # pour trier le menu
  - name: "Bibliothèque des icônes"
    url: "https://fontawesome.com/icons?d=gallery&p=2&m=free"
    weight: 20 # pour trier le menu

  navigation: # menu liens en haut du site 
  - name: "Documentation sur le thème BeeDream"
    url: "https://beedream.billerot.eu/"
    weight: 10
    pre: "help" # nom de l'icône de la bibliothèque des icônes
  - name: "Bibliothèque des icônes"
    url: "https://fontawesome.com/icons?d=gallery&p=2&m=free"
    weight: 20 # pour trier le menu
    pre: "font-awesome" # nom de l'icône de la bibliothèque des icônes
