#
# Configuration par défaut lié au thème
# à redéfinir dans /data/config.yaml
#
title: "TITRE DU SITE"
subtitle: "Sous-titre du site"

# l'image arrondie
avatar: "/img/hugo.png"

# l'icône dans l'onglet du navigateur
favicon: "/img/hugoSM.png"

# l'image d'arrière
backgroundImage: "/img/hugo-background.jpg"

# Liens barre de navigation en haut
params:
  help: "https://beedream.billerot.eu/"
  github: "https://github.com/pbillerot/beedream"
  hugo: "https://gohugo.io/"