#
# Configuration du site
# à recopier dans /config.yaml
#

# Obligatoirement dans /config.yaml 
# Thème utilisé 
theme: "beedream"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: friendly # monokai dracula friendly

# Optionnel car redéfinissable dans /data/config.yaml
# TITRE
params:
  title: "TITRE DU SITE"
  subtitle: "Sous-titre du site"
  # l'image arrondie
  avatar: "/img/hugo.png"
  # l'icône dans l'onglet du navigateur
  favicon: "/img/hugoSM.png"
  # l'image d'arrière
  backgroundImage: "/img/hugo-background.jpg"

