#
# Configuration par défaut lié au thème
# à personnaliser dans /data/config.yaml
#

# TITRE
baseURL: "/"

params:
  title: "TITRE DU SITE"
  subtitle: "Sous-titre du site"
  # l'image arrondie
  avatar: "/img/bee.svg"
  # l'icône dans l'onglet du navigateur
  favicon: "/img/bee.svg"
  # l'image d'arrière
  backgroundImage: "/img/honey.jpg"

  background: "lightsteelblue" 
  linkColor: "seagreen"
  rss: true

  email: "philippe.billerot@gmail.com"
  siteStartYear: 2021
  version: "1.5 du 15 aout 2021"

  enableGitInfo: true

  # Url du site pour éditer les pages directement avec Victor en local
  # Utilisation href="{{printf .Site.Params.HugoServerAdmin .Page.path}}"
  HugoServerAdmin: "http://localhost:8080/victor/document/%s"
  
  enableRobotsTXT: true

  enableSearch: false

  # Url
  help: "https://www.billerot.eu/beedream"
  github: "https://github.com/pbillerot/beedream"
  hugo: "https://gohugo.io/"
  victor: "https://github.com/pbillerot/victor"

# CONFIG lié au thème
languageCode: "fr-FR"
defaultContentLanguage: "fr"
RelativeURLs: true
CanonifyURLs: true
theme: "beedream"
outputs:
  home: ["HTML", "RSS", "JSON"]
# Rendu du markdown
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: friendly # monokai dracula friendly
