#
# Configuration par défaut lié au thème
# à personnaliser dans /data/config.yaml
#

# TITRE
baseURL: "/"
languageCode: "fr-FR"
defaultContentLanguage: "fr"

RelativeURLs: true
CanonifyURLs: true

params:
  title: "TITRE DU SITE"
  subtitle: "Sous-titre du site"
  # l'image arrondie
  avatar: "/img/bee.svg"
  # l'icône dans l'onglet du navigateur
  favicon: "/img/hugoSM.png"
  # l'image d'arrière
  # backgroundImage: "/img/bg-bee.svg"

  background: "DarkSeaGreen" # tan DarkSeaGreen CadetBlue
  linkColor: "seagreen"
  rss: true

  email: "philippe.billerot@gmail.com"
  siteStartYear: 2021
  version: "1.2.1 du 18 avril 2021"

  enableGitInfo: true

  # Url du site pour éditer les pages directement avec Victor en local
  # Utilisation href="{{printf .Site.Params.HugoServerAdmin .Page.path}}"
  HugoServerAdmin: "http://localhost:8080/victor/document/%s"
  
  enableRobotsTXT: true

  enableSearch: false

  advanced:
    customCSS:
    - "css/custom.css"
    customJS:

  # Url
  help: "https://beedream.billerot.eu/"
  github: "https://github.com/pbillerot/beedream"
  hugo: "https://gohugo.io/"
  victor: "https://github.com/pbillerot/victor"

outputs:
  home: ["HTML", "RSS", "JSON"]
